#!/usr/bin/env bash
#using scp to transfer files

if (($# < 4)); then
        echo "0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
        scp -i "$4" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q  "$1" "$3"@"$2":~/ 
fi
