#!/usr/bin/env bash
#setting up nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > somepage.html
sudo cp somepage.html /var/www/html/index.html
