#!/usr/bin/env bash
#setting up nginx
sudo apt update
sudo apt-get -y install nginx
sudo apt-get -y install ufw
sudo ufw --force enable
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 22/tcp
echo "Hello World!" > somepage.html
sudo cp somepage.html /var/www/html/index.html
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo nginx -s reload
