#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

MY_ID=13234

sudo apt-get -y update
sudo apt-get install haproxy -y
echo "
frontend web-frontend
    bind *:80
    default_backend web-backend
backend web-backend
    balance roundrobin
    server $MY_ID-web-01 44.200.43.53:80 check
    server $MY_ID-web-02 3.238.104.57:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart