#!/usr/bin/env bash
# Display "Best School" 10 times or luck

i=0
while ((i++ < 10))
do
	if ((i == 4))
	then
		echo "bad luck"
	elif ((i == 8))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
